### ISSUE TITLE
Intellisense missing

### ISSUE THREAD

**Issue by Sennevds** [Equipple/vs-templates-revit-addin#1]
I recently downloaded your template and it looks really handy to use. One problem is that I don't have any intellisense for the revit api. Is their a way to use intellisense(like setting the version of revit when writing code)

**Comment by salaros** [comment]
@Sennevds I will investigate on this issue in few days, since I'm on a business trip now.
Please make sure you star this project if you really like it, by doing so you will motivate me to do further development of Revit VS template 😅

**Comment by salaros** [comment]
@Sennevds hm, I cloud try to include one of Revit API DLLs without any target framework condition in order to fix IntelliSense . Thanks for the tip

**Comment by salaros** [comment]
Could not reproduce with Visual Studio 2019 and the latest template
