### ISSUE TITLE
Binding to Autodesk.Revit.SDK Nuget Design Time Errors

### ISSUE THREAD

**Issue by kraftwerk15** [Equipple/vs-templates-revit-addin#7]
I'm referencing the Autodesk.Revit.SDK and I have modified my .csproj file to match what is noted here: 
https://github.com/Equipple/vs-templates-revit-addin/blob/f099a5f91980c4b53f336705788fcb0820a326cc/src/RevitAddin.csproj#L105

Whenever I do this, only one version of the package is available during design time.
![image](https://user-images.githubusercontent.com/30668448/80037579-77af1300-84b9-11ea-968e-1560a5a96d49.png)

My .csproj for reference:
![image](https://user-images.githubusercontent.com/30668448/80037632-91e8f100-84b9-11ea-9cac-5ed9663a2abd.png)

Any thoughts on this issue?

**Comment by salaros** [comment]
Hi @kraftwerk15, thanks for using this template.
Could you please take a screenshot or copy paste the upper part of your project, where it says `<TargetFramework>` or `<TargetFrameworks>`?

**Comment by kraftwerk15** [comment]
@salaros 
After I made the changes to all of the projects in Visual Studio, it was still giving me errors in the dependencies. I closed VS and reopened. No Issues.

![image](https://user-images.githubusercontent.com/30668448/80105931-d1a5ec00-853e-11ea-971e-593c84e6376b.png)
